### ISSUE TITLE
Doesn't seem to work with VS 2015 RC

### ISSUE THREAD

**Issue by tyoma** [tyoma/micro-profiler#23]
VS 2013 shows the respective "Enable Profiling" options, but nothing shows up in VS 2015 RC. :(
- Did both a repair. Didn't work.
- Did a remove and install. Didn't work.

Some more information:
- MicroProfiler shows up in the About box
- I'm building a native x86 EXE.

Rui Figueira (Cloudgine) Written June 04, 2015

**Comment by tyoma** [comment]
Probably they changed something in Menu structure in 2015 RC (I tested only with Beta). Will check.

**Comment by rustyx** [comment]
Any news on this? It doesn't seem to work at all in VS 2015 Pro or Community.

**Comment by tyoma** [comment]
Fixed as of 1.1.590. Please, get the latest version on VS gallery site.

**Comment by rustyx** [comment]
Strange because the [VS gallery page](https://visualstudiogallery.msdn.microsoft.com/133d5764-b32b-4ec9-8ee8-5546eca64584) still shown version "1.1.581".

But 1.1.590 does seem to work, thanks!

**Comment by tyoma** [comment]
Updated the page to 1.1.590
I'd really appreciate your stars/following on github and review on VS Gallery! Thanks!
